name = "sub-store-workers"
compatibility_date = "2023-07-19"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
minify = true

[[d1_databases]]
binding = "DB"
database_name = "sub_store"
database_id = "ce47fc64-ce52-45c2-8b30-300d6826b06b"

[vars]
BEARER_TOKEN = "sHHCGFUYxBWQ"
D_TOKEN = "abjAjlTMAys2"
